name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libx11-dev libasound2-dev libudev-dev libxi-dev libxcursor-dev libvulkan-dev

    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Check trailing whitespace
      run: |
        find src -name \*.rs -exec sed -i 's/  *\$//' '{}' \;
        git diff --exit-code

    - name: Check
      run: cargo check --verbose

    - name: Clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose
